require "rake/testtask"


task default:  'run:board'

rule ".hex" => ".a80" do |t|
  sh "asm80 #{t.source}"
end

namespace :run do
  desc "Run board"
  task :board => 'seven_segment.hex' do
    sh 'ruby board.rb'
  end
end
