require "rake/testtask"


task default:  'run:board'

desc "Assemble board.a80"
file 'seven_segment.hex' => 'seven_segment.a80' do
  sh 'asm80 seven_segment.a80'
end

namespace :run do
  desc "Run board"
  task :board => 'seven_segment.hex' do
    sh 'ruby board.rb'
  end
end
