require "rake/testtask"


task default:  'run:board'

rule ".hex" => ".a80" do |t|
  sh "asm80 #{t.source}"
end

namespace :run do
  desc "Run board"
  task :board => 'seven_segment.hex' do
    sh 'ruby board.rb'
  end

  desc "Run TK-80"
  task :tk80 => 'tk80_mon.hex' do
    sh 'ruby board.rb tk80_mon.hex'
  end
end

desc "Run tests"
Rake::TestTask.new do |t|
  t.libs << "../../lib"
  t.libs << "."
  t.libs << "test"
  t.test_files = Dir["test/**/test_*.rb"]
end
